spring:
    data:
     mongodb:
       host: ds029486.mlab.com
       port: 37101
       database: arsw
       username: juan
       password: juan  
    redis:
        host: 192.168.56.102
        port: 6379
        #password: